default:
  tags:
    - DRP19, backend

build:
  stage: build
  script:
    - ./mvnw compile

test:
  stage: test
  script:
    - ./mvnw test

deploy-staging:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_TOKEN

deploy-production:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_TOKEN
  only:
    - master
