default:
  tags:
    - DRP19, backend

build:
  stage: build
  script:
    - ./mvnw compile
  only:
    - master

test:
  stage: test
  script:
    - ./mvnw test
  only:
    - master

deploy-build:
  stage: deploy
  script:
    - ./mvnw clean install
  only:
    - master

deploy-prod:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
